apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: jca-app
  name: jca-app
  namespace: john-c-anthony
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jca-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: jca-app
    spec:
      containers:
      - image: gcr.io/getwrekt-157420/john-anthony-app:v1
        imagePullPolicy: IfNotPresent
        name: jca-app
        ports:
        - containerPort: 8081
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
